#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawn } from 'node:child_process';
import { App } from '../app.js';
import { loadConfig } from '../config.js';
import { validateClassifierWithFallback } from '../classifier/index.js';
import { waitForHealth } from './health-probe.js';

const AGENT_FEED_DIR = path.join(os.homedir(), '.agent-feed');
const PID_FILE = path.join(AGENT_FEED_DIR, 'agent-feed.pid');
const LOG_FILE = path.join(AGENT_FEED_DIR, 'agent-feed.log');
const CONFIG_FILE = path.join(AGENT_FEED_DIR, 'config.toml');
const ENV_FILE = path.join(AGENT_FEED_DIR, 'env');
const PROXY_ENV_VARS = [
  'ANTHROPIC_BASE_URL', 'OPENAI_BASE_URL', 'GOOGLE_API_BASE_URL',
  'GOOGLE_GEMINI_BASE_URL', 'CODE_ASSIST_ENDPOINT',
  // OTel ingestion (Claude + Gemini support these directly; Codex requires
  // editing ~/.codex/config.toml — agent-feed env prints the snippet)
  'CLAUDE_CODE_ENABLE_TELEMETRY',
  'OTEL_EXPORTER_OTLP_PROTOCOL', 'OTEL_EXPORTER_OTLP_ENDPOINT',
  'OTEL_LOG_USER_PROMPTS', 'OTEL_LOG_TOOL_CONTENT', 'OTEL_LOG_RAW_API_BODIES',
  'OTEL_RESOURCE_ATTRIBUTES',
  'GEMINI_TELEMETRY_ENABLED', 'GEMINI_TELEMETRY_TARGET',
  'GEMINI_TELEMETRY_OTLP_ENDPOINT', 'GEMINI_TELEMETRY_OTLP_PROTOCOL',
  'GEMINI_TELEMETRY_LOG_PROMPTS',
];

function waitForFile(filePath, childProcess, timeoutMs = 10000) {
  return new Promise((resolve, reject) => {
    const start = Date.now();
    const check = () => {
      if (fs.existsSync(filePath)) { resolve(); }
      else if (Date.now() - start > timeoutMs) { reject(new Error(`Timed out waiting for ${path.basename(filePath)} after ${timeoutMs / 1000}s. Check logs: ${LOG_FILE}`)); }
      else { setTimeout(check, 100); }
    };
    childProcess.on('exit', (code) => {
      if (code !== 0) reject(new Error(`Process exited with code ${code}. Check logs: ${LOG_FILE}`));
    });
    check();
  });
}

function ensureDir() {
  if (!fs.existsSync(AGENT_FEED_DIR)) {
    fs.mkdirSync(AGENT_FEED_DIR, { recursive: true });
  }
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function writePid(pid) {
  fs.writeFileSync(PID_FILE, String(pid));
}

function readPid() {
  if (!fs.existsSync(PID_FILE)) return null;
  const raw = fs.readFileSync(PID_FILE, 'utf8').trim();
  return raw ? parseInt(raw, 10) : null;
}

function clearPid() {
  try { fs.unlinkSync(PID_FILE); } catch (err) {
    if (err.code !== 'ENOENT') throw err;
  }
}

function clearState() {
  clearPid();
  clearEnvFile();
}

function writeEnvFile(port, otelPort = null) {
  const base = `http://localhost:${port}`;
  const lines = [
    '# Auto-generated by agent-feed — do not edit',
    `export ANTHROPIC_BASE_URL=${base}`,
    `export OPENAI_BASE_URL=${base}/v1`,
    `export GOOGLE_API_BASE_URL=${base}`,
    `export GOOGLE_GEMINI_BASE_URL=${base}`,
    `export CODE_ASSIST_ENDPOINT=${base}`,
  ];
  if (otelPort) {
    const otlp = `http://127.0.0.1:${otelPort}`;
    lines.push(
      '# --- OTel ingestion (Claude Code + Gemini CLI) ---',
      'export CLAUDE_CODE_ENABLE_TELEMETRY=1',
      'export OTEL_EXPORTER_OTLP_PROTOCOL=http/json',
      `export OTEL_EXPORTER_OTLP_ENDPOINT=${otlp}`,
      'export OTEL_LOG_USER_PROMPTS=1',
      'export OTEL_LOG_TOOL_CONTENT=1',
      'export OTEL_LOG_RAW_API_BODIES=1',
      // $(pwd) is intentionally unescaped so the shell evaluates it lazily
      // each time the env file is sourced. Sourcing once and `cd`ing later
      // will leave the cwd attribute stale until the next source.
      'export OTEL_RESOURCE_ATTRIBUTES="process.cwd=$(pwd)"',
      'export GEMINI_TELEMETRY_ENABLED=true',
      'export GEMINI_TELEMETRY_TARGET=local',
      `export GEMINI_TELEMETRY_OTLP_ENDPOINT=${otlp}`,
      'export GEMINI_TELEMETRY_OTLP_PROTOCOL=http',
      'export GEMINI_TELEMETRY_LOG_PROMPTS=true',
      '# Codex CLI does not honor OTLP env vars — paste the following into ~/.codex/config.toml:',
      '#   [otel]',
      `#   exporter = { otlp-http = { endpoint = "${otlp}/v1/logs" } }`,
      '#   log_user_prompt = true',
    );
  }
  lines.push('');
  // Atomic write: temp file + rename. Prevents readers (shell-init source-loads
  // and `agent-feed env` reads) from seeing a partial file if writeEnvFile is
  // killed mid-write.
  const tmp = ENV_FILE + '.tmp';
  fs.writeFileSync(tmp, lines.join('\n'));
  fs.renameSync(tmp, ENV_FILE);
}

function clearEnvFile() {
  try { fs.unlinkSync(ENV_FILE); } catch (err) {
    if (err.code !== 'ENOENT') throw err;
  }
}

async function isPortInUse(port) {
  const net = await import('node:net');
  return new Promise((resolve) => {
    const server = net.createServer();
    server.once('error', () => resolve(true));
    server.once('listening', () => { server.close(); resolve(false); });
    server.listen(port, 'localhost');
  });
}

function isProcessRunning(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

// Send SIGTERM, wait for the process to exit, then SIGKILL if it didn't.
// Used by stop/restart and by cmdStart's failure-recovery path to ensure no
// orphan supervisor lingers and races the next start. Returns true if the
// process is gone after the call (regardless of how it died).
async function killAndWait(pid, { timeoutMs = 5000 } = {}) {
  if (!pid || !isProcessRunning(pid)) return true;
  try { process.kill(pid, 'SIGTERM'); } catch {}
  const deadline = Date.now() + timeoutMs;
  while (isProcessRunning(pid) && Date.now() < deadline) {
    await new Promise(r => setTimeout(r, 100));
  }
  if (isProcessRunning(pid)) {
    try { process.kill(pid, 'SIGKILL'); } catch {}
    await new Promise(r => setTimeout(r, 200));
  }
  return !isProcessRunning(pid);
}

function log(msg) {
  const line = `[${new Date().toISOString()}] ${msg}\n`;
  fs.appendFileSync(LOG_FILE, line);
}

async function cmdStart({ verbose = false, daemon = false } = {}) {
  ensureDir();

  const existingPid = readPid();
  if (existingPid && isProcessRunning(existingPid)) {
    console.error(`Agent Feed is already running (PID ${existingPid})`);
    process.exit(1);
  }

  // Supervisor mode: detached process that owns the daemon child and restarts on crash
  const supervisor = process.env.AGENT_FEED_SUPERVISOR === '1';

  if (!verbose && !daemon && !supervisor) {
    // CLI foreground: fork the supervisor as a detached process, print status, exit
    const config = loadConfig(CONFIG_FILE);
    console.log('Starting Agent Feed...');

    const logFd = fs.openSync(LOG_FILE, 'a');
    const sup = spawn(process.execPath, [process.argv[1], 'start', '--daemon'], {
      detached: true,
      stdio: ['ignore', logFd, logFd],
      env: { ...process.env, AGENT_FEED_SUPERVISOR: '1' },
    });
    fs.closeSync(logFd);
    sup.unref();

    // Wait for the daemon to actually serve requests, not just spawn. The
    // health probe queries `/api/health` which requires the UI server is
    // listening AND the DB is queryable — catches migration crashes that
    // would otherwise leave us with stranded env vars on a dead port.
    const health = await waitForHealth(config.ui.port);
    if (!health.ok) {
      // Daemon failed to come up. Remove env file so NEW shells don't get
      // exports pointing at a dead port; tell the current shell how to
      // unset; tear down any leftover supervisor that might respawn and
      // race the user's next start.
      clearEnvFile();
      await killAndWait(sup.pid ?? readPid(), { timeoutMs: 2000 });
      clearPid();
      // The supervisor's signal handler should have killed its daemon child
      // before exiting, but if SIGTERM didn't propagate (e.g. supervisor
      // already SIGKILL'd) the child may still be holding ports. Check and
      // warn so the user can `lsof` and clean up before retrying.
      const stillBoundPorts = [];
      for (const port of [config.proxy.port, config.ui.port, config.otel?.port].filter(Boolean)) {
        if (await isPortInUse(port)) stillBoundPorts.push(port);
      }
      const portWarning = stillBoundPorts.length > 0
        ? `\n\n⚠ Ports still bound by an orphaned process: ${stillBoundPorts.join(', ')}` +
          `\n  Find and kill: lsof -nP -iTCP:${stillBoundPorts.join(' -iTCP:')} -sTCP:LISTEN`
        : '';
      console.error(
        `\n✗ Agent-feed daemon failed to become healthy within 30s.` +
        `\n  Last error: ${health.lastError}` +
        `\n  Log: ${LOG_FILE}` +
        portWarning +
        `\n\nYour CURRENT shell still has these env vars exported. Run:\n\n  unset ${PROXY_ENV_VARS.join(' ')}` +
        `\n\n…or open a new terminal. Until you do, coding agents will hang on a dead port.\n`
      );
      process.exit(1);
    }

    // Read back what the supervisor wrote
    const envStart = Date.now();
    while (!fs.existsSync(PID_FILE) && Date.now() - envStart < 3000) {
      await new Promise(r => setTimeout(r, 50));
    }
    const pid = readPid();
    const envContent = fs.existsSync(ENV_FILE) ? fs.readFileSync(ENV_FILE, 'utf8') : '';
    const portMatch = envContent.match(/localhost:(\d+)/);
    const actualPort = portMatch ? portMatch[1] : config.proxy.port;
    console.log(`  ✓ Proxy listening on :${actualPort}`);
    console.log(`  ✓ Web UI available at http://localhost:${config.ui.port}`);
    console.log(`  ✓ Environment file written (~/.agent-feed/env)`);
    console.log(`Agent Feed running (PID ${pid}), logs: ${LOG_FILE}`);
    process.exit(0);
  }

  // Supervisor process: fork daemon, monitor, restart on crash
  if (supervisor) {
    function forkDaemon() {
      const { AGENT_FEED_SUPERVISOR: _, ...daemonEnv } = process.env;
      const logFd = fs.openSync(LOG_FILE, 'a');
      const child = spawn(process.execPath, [process.argv[1], 'start', '--daemon'], {
        detached: false,
        stdio: ['ignore', logFd, logFd],
        env: daemonEnv,
      });
      fs.closeSync(logFd);
      return child;
    }

    let child = forkDaemon();
    let shuttingDown = false;

    await waitForFile(ENV_FILE, child);

    // Supervisor owns the PID file
    writePid(process.pid);

    let restartCount = 0;
    let lastRestartTime = 0;
    const MAX_RESTARTS = 5;
    const RESTART_WINDOW = 60_000;

    function supervise(c) {
      c.on('exit', (code) => {
        // During shutdown the supervisor itself is responsible for exit;
        // skip restart logic so we don't fork a new daemon while teardown
        // is in progress.
        if (shuttingDown) return;

        if (code === 0) {
          clearState();
          process.exit(0);
        }

        const now = Date.now();
        if (now - lastRestartTime > RESTART_WINDOW) restartCount = 0;
        lastRestartTime = now;
        restartCount++;

        if (restartCount > MAX_RESTARTS) {
          log(`daemon crashed ${MAX_RESTARTS} times in ${RESTART_WINDOW / 1000}s, giving up`);
          clearState();
          process.exit(1);
        }

        const delay = Math.min(1000 * 2 ** (restartCount - 1), 10_000);
        log(`daemon exited with code ${code}, restarting in ${delay}ms (attempt ${restartCount}/${MAX_RESTARTS})`);

        setTimeout(() => {
          child = forkDaemon();
          supervise(child);
        }, delay);
      });
    }

    // Forward SIGTERM/SIGINT to the daemon child, wait for it to release
    // its ports (proxy 18080, ui 3000, otel 4318), then exit. Without this
    // the child orphans and `agent-feed start` after `stop` would hit
    // EADDRINUSE during respawn-backoff.
    for (const sig of ['SIGTERM', 'SIGINT']) {
      process.on(sig, async () => {
        if (shuttingDown) return;
        shuttingDown = true;
        if (child && !child.killed) {
          child.kill(sig);
          await new Promise((resolve) => {
            const killTimer = setTimeout(() => {
              try { child.kill('SIGKILL'); } catch {}
              resolve();
            }, 3000);
            child.once('exit', () => {
              clearTimeout(killTimer);
              resolve();
            });
          });
        }
        clearState();
        process.exit(0);
      });
    }

    supervise(child);
    return;
  }

  const config = loadConfig(CONFIG_FILE);

  if (await isPortInUse(config.proxy.port)) {
    const msg = `Port ${config.proxy.port} is already in use. Run 'agent-feed stop' or check for orphaned processes.`;
    console.error(msg);
    log(msg);
    process.exit(1);
  }

  const app = new App({ config, verbose });

  // Validate classifier before starting anything else
  // (App.start() will throw if classifier is unreachable)
  try {
    await app.start();
  } catch (err) {
    const reason = err.message ?? String(err);
    console.error(`  ✗ ${reason}`);
    console.error('\nAgent Feed failed to start. Resolve the above and try again.');
    log(`startup failed: ${reason}`);
    await app.stop().catch(() => {});
    process.exit(1);
  }

  const status = app.getStatus();
  const dbSize = formatBytes(status.dbSizeBytes);
  const classifierLabel = status.classifierLabel ?? config.classifier.provider;
  const configuredProvider = config.classifier.provider;
  const actualProvider = status.classifierLabel?.split('/')[0];
  const fallbackNote = actualProvider && actualProvider !== configuredProvider
    ? ` (fallback from ${configuredProvider})`
    : '';

  // PID file written by supervisor in daemon mode; only write here in verbose mode
  if (verbose) writePid(process.pid);
  writeEnvFile(status.proxyPort, status.otelPort);
  const otelTag = status.otelPort ? `, otel :${status.otelPort}` : '';
  log(`started -- proxy :${status.proxyPort}, ui :${status.uiPort}${otelTag}`);

  const shutdown = async () => {
    if (verbose) console.log('\nStopping Agent Feed...');
    log('shutting down');
    try { await app.stop(); } finally {
      clearState();
      if (verbose) console.log('Run: unset ' + PROXY_ENV_VARS.join(' '));
      process.exit(0);
    }
  };
  process.on('SIGTERM', shutdown);
  process.on('SIGINT', shutdown);

  // WHY: Log and EXIT on fatal errors, never log-and-continue — Node docs warn that
  // process state is unreliable after uncaughtException. In daemon mode the supervisor
  // detects the non-zero exit and re-forks. clearState() is only called in verbose
  // mode because the supervisor owns the PID file in daemon mode.
  let fatalShutdown = false;
  process.on('uncaughtException', async (err) => {
    if (fatalShutdown) { process.exit(1); return; }
    fatalShutdown = true;
    log(`FATAL uncaught exception: ${err.stack ?? err}`);
    try { await app.stop(); } catch {}
    if (verbose) clearState(); // only in verbose mode (no supervisor)
    process.exit(1);
  });
  process.on('unhandledRejection', (reason) => {
    log(`FATAL unhandled rejection: ${reason}`);
    // Node 15+ would throw unhandled rejections by default. Without this exit,
    // this handler downgrades that to log-and-continue — contradicting the
    // "log and EXIT" design decision above. Match uncaughtException behavior.
    process.exit(1);
  });

  if (verbose) {
    console.log('Starting Agent Feed...');
    console.log(`  ✓ Proxy listening on :${status.proxyPort}`);
    console.log(`  ✓ Classifier ready (${classifierLabel}${fallbackNote})`);
    console.log(`  ✓ Web UI available at http://localhost:${status.uiPort}`);
    console.log(`  ✓ SQLite initialized at ${config.storage.path} (${dbSize})`);
    console.log('Agent Feed ready.');
    console.log('\n[verbose] Logging to', LOG_FILE);
    console.log('[verbose] Press Ctrl+C to stop\n');
    process.stdin.resume();
  } else {
    log(`proxy :${status.proxyPort}, classifier: ${classifierLabel}${fallbackNote}, ui :${status.uiPort}, db: ${dbSize}`);
  }
}

async function cmdStop() {
  const pid = readPid();
  if (!pid) {
    console.error('Agent Feed is not running (no PID file found)');
    process.exit(1);
  }
  if (!isProcessRunning(pid)) {
    console.error(`Agent Feed process (PID ${pid}) is not running -- cleaning up`);
    clearState();
    process.exit(0);
  }
  await killAndWait(pid);
  clearState();
  console.log(`Agent Feed stopped (PID ${pid})`);
  console.log('Run: unset ' + PROXY_ENV_VARS.join(' '));
}

async function cmdRestart() {
  const pid = readPid();
  if (pid && isProcessRunning(pid)) {
    console.log('Stopping Agent Feed...');
    await killAndWait(pid);
    clearState();
    console.log(`Agent Feed stopped (PID ${pid})`);
  } else {
    if (pid) clearState(); // clean up stale PID
    console.log('Agent Feed is not running, starting fresh...');
  }

  await cmdStart();
}

async function cmdEval(subcommand) {
  const validSubcommands = ['classifier', 'show'];
  if (!validSubcommands.includes(subcommand)) {
    console.error(`Unknown eval target: ${subcommand}`);
    console.error('Usage:');
    console.error('  agent-feed eval classifier   Precision/recall report');
    console.error('  agent-feed eval show         Show missed flags and false positives');
    process.exit(1);
  }

  ensureDir();
  const config = loadConfig(CONFIG_FILE);
  const dbPath = config.storage.path.startsWith('~')
    ? path.join(os.homedir(), config.storage.path.slice(1))
    : config.storage.path;

  if (!fs.existsSync(dbPath)) {
    console.error(`Database not found at ${dbPath}. Run agent-feed start first.`);
    process.exit(1);
  }

  const { Database } = await import('../storage/database.js');
  const { buildClassifier, validateClassifierWithFallback } = await import('../classifier/index.js');
  const { runClassifierEval, getEvalExamples, formatEvalReport, formatEvalExamples } = await import('../eval.js');

  const db = new Database(dbPath);
  await db.init();

  const validation = await validateClassifierWithFallback(config.classifier);
  if (!validation.ok) {
    console.error(`Classifier unreachable: ${validation.reason}`);
    process.exit(1);
  }

  const classifierFn = buildClassifier(validation.effectiveConfig);

  if (subcommand === 'classifier') {
    console.log('Running classifier eval...');
    const report = await runClassifierEval({ db, classifierFn });
    await db.close();
    console.log('');
    console.log(formatEvalReport(report));
  } else if (subcommand === 'show') {
    console.log('Loading eval examples...');
    const examples = await getEvalExamples({ db, classifierFn });
    await db.close();
    console.log('');
    console.log(formatEvalExamples(examples));
  }
}

function cmdEnv() {
  const pid = readPid();
  const running = pid && isProcessRunning(pid);

  if (running && fs.existsSync(ENV_FILE)) {
    process.stdout.write(fs.readFileSync(ENV_FILE, 'utf8'));
  } else {
    // Cleanup stale state
    if (pid && !isProcessRunning(pid)) {
      clearState();
    }
    for (const v of PROXY_ENV_VARS) console.log(`unset ${v}`);
  }
}

function cmdShellInit() {
  const snippet = `# agent-feed shell integration
agent-feed() {
  command agent-feed "$@"
  local rc=$?
  if [[ "$1" == "start" || "$1" == "stop" || "$1" == "restart" ]]; then
    eval "$(command agent-feed env)"
  fi
  return $rc
}

# Auto-source env if proxy is running
if [[ -f ~/.agent-feed/env ]]; then
  _af_pid=""
  [[ -f ~/.agent-feed/agent-feed.pid ]] && _af_pid=$(cat ~/.agent-feed/agent-feed.pid 2>/dev/null)
  if [[ -n "$_af_pid" ]] && kill -0 "$_af_pid" 2>/dev/null; then
    source ~/.agent-feed/env
  else
    rm -f ~/.agent-feed/env ~/.agent-feed/agent-feed.pid
  fi
  unset _af_pid
fi`;
  console.log(snippet);
}

// Parse CLI args
const args = process.argv.slice(2);
const command = args[0];
const verbose = args.includes('--verbose');
const daemon = args.includes('--daemon');

switch (command) {
  case 'start':
    await cmdStart({ verbose, daemon });
    break;
  case 'stop':
    await cmdStop();
    break;
  case 'restart':
    await cmdRestart();
    break;
  case 'eval':
    await cmdEval(args[1]);
    break;
  case 'env':
    cmdEnv();
    break;
  case 'shell-init':
    cmdShellInit();
    break;
  default:
    console.log('Usage:');
    console.log('  agent-feed start               Start proxy, classifier, and UI in background');
    console.log('  agent-feed start --verbose      Start in foreground with diagnostic logging');
    console.log('  agent-feed stop                 Stop all services');
    console.log('  agent-feed restart              Stop and restart all services');
    console.log('  agent-feed eval classifier      Run classifier precision/recall eval');
    console.log('  agent-feed eval show            Show missed flags and false positives');
    console.log('  agent-feed env                  Print shell env vars (source with eval)');
    console.log('  agent-feed shell-init           Print shell integration snippet for .zshrc');
    process.exit(command ? 1 : 0);
}
