#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawn } from 'node:child_process';
import { App } from '../app.js';
import { loadConfig } from '../config.js';
import { validateClassifierWithFallback } from '../classifier/index.js';

const AGENT_FEED_DIR = path.join(os.homedir(), '.agent-feed');
const PID_FILE = path.join(AGENT_FEED_DIR, 'agent-feed.pid');
const LOG_FILE = path.join(AGENT_FEED_DIR, 'agent-feed.log');
const CONFIG_FILE = path.join(AGENT_FEED_DIR, 'config.toml');
const ENV_FILE = path.join(AGENT_FEED_DIR, 'env');

function ensureDir() {
  if (!fs.existsSync(AGENT_FEED_DIR)) {
    fs.mkdirSync(AGENT_FEED_DIR, { recursive: true });
  }
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function writePid(pid) {
  fs.writeFileSync(PID_FILE, String(pid));
}

function readPid() {
  if (!fs.existsSync(PID_FILE)) return null;
  const raw = fs.readFileSync(PID_FILE, 'utf8').trim();
  return raw ? parseInt(raw, 10) : null;
}

function clearPid() {
  if (fs.existsSync(PID_FILE)) fs.unlinkSync(PID_FILE);
}

function writeEnvFile(port) {
  const base = `http://localhost:${port}`;
  const lines = [
    '# Auto-generated by agent-feed — do not edit',
    `export ANTHROPIC_BASE_URL=${base}/anthropic`,
    `export OPENAI_BASE_URL=${base}/openai`,
    `export GOOGLE_API_BASE_URL=${base}/google`,
    ''
  ];
  fs.writeFileSync(ENV_FILE, lines.join('\n'));
}

function clearEnvFile() {
  try { fs.unlinkSync(ENV_FILE); } catch {}
}

function isProcessRunning(pid) {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

function log(msg) {
  const line = `[${new Date().toISOString()}] ${msg}\n`;
  fs.appendFileSync(LOG_FILE, line);
}

async function cmdStart({ verbose = false, daemon = false } = {}) {
  ensureDir();

  const existingPid = readPid();
  if (existingPid && isProcessRunning(existingPid)) {
    console.error(`Agent Feed is already running (PID ${existingPid})`);
    process.exit(1);
  }

  // Fork a detached daemon when not in verbose or daemon mode
  if (!verbose && !daemon) {
    const config = loadConfig(CONFIG_FILE);
    console.log('Starting Agent Feed...');

    const logFd = fs.openSync(LOG_FILE, 'a');
    const child = spawn(process.execPath, [process.argv[1], 'start', '--daemon'], {
      detached: true,
      stdio: ['ignore', logFd, logFd],
      env: { ...process.env, AGENT_FEED_DAEMON: '1' },
    });
    fs.closeSync(logFd);
    child.unref();

    // Poll for PID file to confirm daemon started
    const timeout = 10000;
    const start = Date.now();
    await new Promise((resolve, reject) => {
      const check = () => {
        if (fs.existsSync(PID_FILE)) {
          resolve();
        } else if (Date.now() - start > timeout) {
          reject(new Error('Startup timed out after 10s. Check logs: ' + LOG_FILE));
        } else {
          setTimeout(check, 100);
        }
      };
      child.on('exit', (code) => {
        if (code !== 0) reject(new Error(`Daemon process exited with code ${code}. Check logs: ${LOG_FILE}`));
      });
      check();
    });

    const pid = readPid();
    writeEnvFile(config.proxy.port);
    console.log(`  ✓ Proxy listening on :${config.proxy.port}`);
    console.log(`  ✓ Web UI available at http://localhost:${config.ui.port}`);
    console.log(`  ✓ Environment file written (~/.agent-feed/env)`);
    console.log(`Agent Feed running (PID ${pid}), logs: ${LOG_FILE}`);
    process.exit(0);
  }

  const config = loadConfig(CONFIG_FILE);

  const app = new App({ config });

  // Validate classifier before starting anything else
  // (App.start() will throw if classifier is unreachable)
  try {
    await app.start();
  } catch (err) {
    const reason = err.message ?? String(err);
    console.error(`  ✗ ${reason}`);
    console.error('\nAgent Feed failed to start. Resolve the above and try again.');
    log(`startup failed: ${reason}`);
    await app.stop().catch(() => {});
    process.exit(1);
  }

  const status = app.getStatus();
  const dbSize = formatBytes(status.dbSizeBytes);
  const classifierLabel = status.classifierLabel ?? config.classifier.provider;
  const configuredProvider = config.classifier.provider;
  const actualProvider = status.classifierLabel?.split('/')[0];
  const fallbackNote = actualProvider && actualProvider !== configuredProvider
    ? ` (fallback from ${configuredProvider})`
    : '';

  writePid(process.pid);
  writeEnvFile(status.proxyPort);
  log(`started -- proxy :${status.proxyPort}, ui :${status.uiPort}`);

  if (verbose) {
    console.log('Starting Agent Feed...');
    console.log(`  ✓ Proxy listening on :${status.proxyPort}`);
    console.log(`  ✓ Classifier ready (${classifierLabel}${fallbackNote})`);
    console.log(`  ✓ Web UI available at http://localhost:${status.uiPort}`);
    console.log(`  ✓ SQLite initialized at ${config.storage.path} (${dbSize})`);
    console.log('Agent Feed ready.');
    console.log('\n[verbose] Logging to', LOG_FILE);
    console.log('[verbose] Press Ctrl+C to stop\n');

    const shutdown = async () => {
      console.log('\nStopping Agent Feed...');
      log('shutting down (verbose)');
      try { await app.stop(); } finally {
        clearPid();
        clearEnvFile();
        process.exit(0);
      }
    };
    process.on('SIGINT', shutdown);
    process.on('SIGTERM', shutdown);
    process.stdin.resume();
  } else {
    // daemon mode: log startup details to file, keep process alive
    log(`proxy :${status.proxyPort}, classifier: ${classifierLabel}${fallbackNote}, ui :${status.uiPort}, db: ${dbSize}`);

    const shutdown = async () => {
      log('shutting down');
      try { await app.stop(); } finally {
        clearPid();
        clearEnvFile();
        process.exit(0);
      }
    };
    process.on('SIGTERM', shutdown);
    process.on('SIGINT', shutdown);
  }
}

async function cmdStop() {
  const pid = readPid();
  if (!pid) {
    console.error('Agent Feed is not running (no PID file found)');
    process.exit(1);
  }
  if (!isProcessRunning(pid)) {
    console.error(`Agent Feed process (PID ${pid}) is not running -- cleaning up`);
    clearPid();
    clearEnvFile();
    process.exit(0);
  }
  try {
    process.kill(pid, 'SIGTERM');
    console.log(`Agent Feed stopped (PID ${pid})`);
    clearPid();
    clearEnvFile();
  } catch (err) {
    console.error(`Failed to stop Agent Feed: ${err.message}`);
    process.exit(1);
  }
}

async function cmdEval(subcommand) {
  const validSubcommands = ['classifier', 'show'];
  if (!validSubcommands.includes(subcommand)) {
    console.error(`Unknown eval target: ${subcommand}`);
    console.error('Usage:');
    console.error('  agent-feed eval classifier   Precision/recall report');
    console.error('  agent-feed eval show         Show missed flags and false positives');
    process.exit(1);
  }

  ensureDir();
  const config = loadConfig(CONFIG_FILE);
  const dbPath = config.storage.path.startsWith('~')
    ? path.join(os.homedir(), config.storage.path.slice(1))
    : config.storage.path;

  if (!fs.existsSync(dbPath)) {
    console.error(`Database not found at ${dbPath}. Run agent-feed start first.`);
    process.exit(1);
  }

  const { Database } = await import('../storage/database.js');
  const { buildClassifier, validateClassifierWithFallback } = await import('../classifier/index.js');
  const { runClassifierEval, getEvalExamples, formatEvalReport, formatEvalExamples } = await import('../eval.js');

  const db = new Database(dbPath);
  await db.init();

  const validation = await validateClassifierWithFallback(config.classifier);
  if (!validation.ok) {
    console.error(`Classifier unreachable: ${validation.reason}`);
    process.exit(1);
  }

  const classifierFn = buildClassifier(validation.effectiveConfig);

  if (subcommand === 'classifier') {
    console.log('Running classifier eval...');
    const report = await runClassifierEval({ db, classifierFn });
    await db.close();
    console.log('');
    console.log(formatEvalReport(report));
  } else if (subcommand === 'show') {
    console.log('Loading eval examples...');
    const examples = await getEvalExamples({ db, classifierFn });
    await db.close();
    console.log('');
    console.log(formatEvalExamples(examples));
  }
}

function cmdEnv() {
  const pid = readPid();
  const running = pid && isProcessRunning(pid);

  if (running && fs.existsSync(ENV_FILE)) {
    process.stdout.write(fs.readFileSync(ENV_FILE, 'utf8'));
  } else {
    // Cleanup stale state
    if (pid && !isProcessRunning(pid)) {
      clearPid();
      clearEnvFile();
    }
    console.log('unset ANTHROPIC_BASE_URL');
    console.log('unset OPENAI_BASE_URL');
    console.log('unset GOOGLE_API_BASE_URL');
  }
}

function cmdShellInit() {
  const snippet = `# agent-feed shell integration
agent-feed() {
  command agent-feed "$@"
  local rc=$?
  if [[ "$1" == "start" || "$1" == "stop" ]]; then
    eval "$(command agent-feed env)"
  fi
  return $rc
}

# Auto-source env if proxy is running
if [[ -f ~/.agent-feed/env ]]; then
  _af_pid=""
  [[ -f ~/.agent-feed/agent-feed.pid ]] && _af_pid=$(cat ~/.agent-feed/agent-feed.pid 2>/dev/null)
  if [[ -n "$_af_pid" ]] && kill -0 "$_af_pid" 2>/dev/null; then
    source ~/.agent-feed/env
  else
    rm -f ~/.agent-feed/env ~/.agent-feed/agent-feed.pid
  fi
  unset _af_pid
fi`;
  console.log(snippet);
}

// Parse CLI args
const args = process.argv.slice(2);
const command = args[0];
const verbose = args.includes('--verbose');
const daemon = args.includes('--daemon');

switch (command) {
  case 'start':
    await cmdStart({ verbose, daemon });
    break;
  case 'stop':
    await cmdStop();
    break;
  case 'eval':
    await cmdEval(args[1]);
    break;
  case 'env':
    cmdEnv();
    break;
  case 'shell-init':
    cmdShellInit();
    break;
  default:
    console.log('Usage:');
    console.log('  agent-feed start               Start proxy, classifier, and UI in background');
    console.log('  agent-feed start --verbose      Start in foreground with diagnostic logging');
    console.log('  agent-feed stop                 Stop all services');
    console.log('  agent-feed eval classifier      Run classifier precision/recall eval');
    console.log('  agent-feed eval show            Show missed flags and false positives');
    console.log('  agent-feed env                  Print shell env vars (source with eval)');
    console.log('  agent-feed shell-init           Print shell integration snippet for .zshrc');
    process.exit(command ? 1 : 0);
}
